# Generated by Django 5.2.4 on 2026-08-10 15:32

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinets', '0011_finance_module'),
        ('cases', '0009_finance_module'),
        ('tasks', '0005_delete_case_alter_appointment_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('jurisdiction', models.CharField(db_index=True, default='MA', max_length=8)),
                ('legal_domain', models.CharField(choices=[('civil_procedure', 'Civil Procedure'), ('commercial_procedure', 'Commercial Procedure'), ('labour', 'Labour'), ('family', 'Family'), ('criminal', 'Criminal'), ('administrative', 'Administrative'), ('tax', 'Tax'), ('other', 'Other')], db_index=True, default='civil_procedure', max_length=40)),
                ('procedure_type', models.CharField(choices=[('appeal', 'Appeal'), ('opposition', 'Opposition'), ('cassation', 'Cassation'), ('refere', 'Urgent proceedings / référé'), ('response', 'Response'), ('other', 'Other')], db_index=True, max_length=40)),
                ('event_type', models.CharField(choices=[('notification', 'Official notification'), ('judgment', 'Judgment'), ('filing', 'Filing'), ('service', 'Service / signification'), ('other', 'Other')], default='notification', max_length=40)),
                ('duration_value', models.PositiveIntegerField()),
                ('duration_unit', models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default='days', max_length=16)),
                ('computation_method', models.CharField(choices=[('delai_franc', 'Délai franc'), ('calendar_days', 'Calendar days'), ('business_days', 'Business days')], default='delai_franc', max_length=32)),
                ('exclude_triggering_day', models.BooleanField(default=True, help_text='If True, the triggering event day is not counted (typical for délai franc).')),
                ('adjust_non_working_final_day', models.BooleanField(default=True, help_text='If True and the final day is a weekend/holiday, prorogate to next working day.')),
                ('weekend_days', models.JSONField(blank=True, default=list)),
                ('article_reference', models.CharField(blank=True, max_length=128)),
                ('version', models.CharField(help_text='Immutable version label, e.g. 1974.1 or 2026.1', max_length=32)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('requires_verification', 'Requires legal verification'), ('inactive', 'Inactive')], db_index=True, default='requires_verification', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('special_conditions', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Deadline rule',
                'verbose_name_plural': 'Deadline rules',
                'ordering': ['legal_domain', 'procedure_type', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='LegalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('jurisdiction', models.CharField(db_index=True, default='MA', max_length=8)),
                ('code_name', models.CharField(max_length=255)),
                ('law_number', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=512)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('official_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending entry into force'), ('in_force', 'In force'), ('repealed', 'Repealed')], default='in_force', max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Legal source',
                'verbose_name_plural': 'Legal sources',
                'ordering': ['-effective_from', 'law_number'],
            },
        ),
        migrations.CreateModel(
            name='CalculatedDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('rule_snapshot', models.JSONField(blank=True, default=dict)),
                ('triggering_event_type', models.CharField(max_length=40)),
                ('triggering_date', models.DateField()),
                ('calculated_deadline', models.DateField(help_text='Date produced by the calculation engine (immutable after override).')),
                ('final_deadline', models.DateField(help_text='Effective deadline date (equals calculated unless manually overridden).')),
                ('is_manual_override', models.BooleanField(default=False)),
                ('original_calculated_deadline', models.DateField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('override_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('due_soon', 'Due soon'), ('due_today', 'Due today'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='upcoming', max_length=20)),
                ('calculation_explanation', models.JSONField(blank=True, default=dict)),
                ('contextual_parameters', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_deadlines', to='cabinets.cabinet')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_deadlines', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_deadlines_created', to=settings.AUTH_USER_MODEL)),
                ('linked_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_deadlines', to='tasks.task')),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_deadlines_overridden', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(help_text='Rule version used at calculation time (do not retarget to a newer version).', on_delete=django.db.models.deletion.PROTECT, related_name='calculated_deadlines', to='legal_deadlines.deadlinerule')),
            ],
            options={
                'verbose_name': 'Calculated deadline',
                'verbose_name_plural': 'Calculated deadlines',
                'ordering': ['final_deadline', '-created'],
            },
        ),
        migrations.CreateModel(
            name='LegalHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('jurisdiction', models.CharField(db_index=True, default='MA', max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('holiday_type', models.CharField(choices=[('fixed', 'Fixed national holiday'), ('movable_religious', 'Movable / religious holiday'), ('other', 'Other')], default='fixed', max_length=32)),
                ('is_legally_relevant', models.BooleanField(default=True, help_text='Whether this day may affect deadline prorogation when the rule so provides.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Legal holiday',
                'verbose_name_plural': 'Legal holidays',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('jurisdiction', 'date', 'name'), name='uniq_legal_holiday_jurisdiction_date_name')],
            },
        ),
        migrations.AddField(
            model_name='deadlinerule',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='legal_deadlines.legalsource'),
        ),
        migrations.CreateModel(
            name='DeadlineReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('days_before', models.PositiveIntegerField(help_text='0 = day of deadline; 1 = one day before, etc.')),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadline_reminders_created', to=settings.AUTH_USER_MODEL)),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='legal_deadlines.calculateddeadline')),
            ],
            options={
                'verbose_name': 'Deadline reminder',
                'verbose_name_plural': 'Deadline reminders',
                'ordering': ['-days_before'],
                'constraints': [models.UniqueConstraint(fields=('deadline', 'days_before'), name='uniq_deadline_reminder_offset')],
            },
        ),
        migrations.AddIndex(
            model_name='calculateddeadline',
            index=models.Index(fields=['cabinet', 'final_deadline'], name='legal_deadl_cabinet_8001ce_idx'),
        ),
        migrations.AddIndex(
            model_name='calculateddeadline',
            index=models.Index(fields=['case', 'status'], name='legal_deadl_case_id_bb092e_idx'),
        ),
        migrations.AddConstraint(
            model_name='deadlinerule',
            constraint=models.UniqueConstraint(fields=('code', 'version', 'jurisdiction'), name='uniq_deadline_rule_code_version_jurisdiction'),
        ),
    ]
