# Generated by Django 5.2.4 on 2026-08-10 20:22

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinets', '0011_finance_module'),
        ('cases', '0009_finance_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('search_query', models.CharField(max_length=255)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('REVIEWED_NO_CONFLICT', 'Reviewed — No Conflict'), ('CONFLICT_IDENTIFIED', 'Conflict Identified'), ('WAIVER_REQUIRED', 'Waiver Required'), ('DISMISSED', 'Dismissed')], db_index=True, default='PENDING_REVIEW', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_checks', to='cabinets.cabinet')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflict_checks_initiated', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(blank=True, help_text='Optional matter this check is associated with (e.g. during creation).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflict_checks', to='cases.case')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflict_checks_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PotentialMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('entity_type', models.CharField(choices=[('CLIENT', 'Client'), ('ORGANIZATION', 'Organization'), ('PARTY', 'Party'), ('COUNSEL', 'Counsel'), ('RELATED_PARTY', 'Related Party')], max_length=32)),
                ('entity_id', models.PositiveIntegerField(blank=True, help_text='User id when the entity is a client; null for free-text parties.', null=True)),
                ('entity_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('FORMER_CLIENT', 'Former Client'), ('OPPOSING_PARTY', 'Opposing Party'), ('OPPOSING_COUNSEL', 'Opposing Counsel'), ('THIRD_PARTY', 'Third Party'), ('RELATED_PARTY', 'Related Party'), ('PLAINTIFF', 'Plaintiff'), ('DEFENDANT', 'Defendant'), ('OTHER', 'Other Participant')], default='OTHER', max_length=32)),
                ('match_type', models.CharField(choices=[('EXACT', 'Exact'), ('HIGH', 'High'), ('POSSIBLE', 'Possible')], max_length=16)),
                ('confidence', models.FloatField(default=0.0)),
                ('match_reason', models.CharField(blank=True, default='', max_length=255)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('NO_CONFLICT', 'Reviewed — No Conflict'), ('CONFLICT', 'Conflict Identified'), ('WAIVER', 'Waiver Required'), ('DISMISSED', 'Dismissed')], db_index=True, default='PENDING', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('conflict_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='conflict_checks.conflictcheck')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_potential_matches', to='cases.case')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflict_matches_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence', 'entity_name', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='conflictcheck',
            index=models.Index(fields=['cabinet', '-created'], name='conflict_ch_cabinet_e75ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictcheck',
            index=models.Index(fields=['cabinet', 'search_query'], name='conflict_ch_cabinet_096a47_idx'),
        ),
        migrations.AddIndex(
            model_name='potentialmatch',
            index=models.Index(fields=['conflict_check', 'match_type'], name='conflict_ch_conflic_ea9de5_idx'),
        ),
        migrations.AddIndex(
            model_name='potentialmatch',
            index=models.Index(fields=['matter', 'role'], name='conflict_ch_matter__e05cb2_idx'),
        ),
    ]
