# Generated by Django 5.2.4 on 2026-03-27 21:00

import django.db.models.deletion
from decimal import Decimal

from django.db import migrations, models
from django.db.models import Sum


def seed_firm_settings_and_backfill(apps, schema_editor):
    Cabinet = apps.get_model('cabinets', 'Cabinet')
    FirmFinanceSettings = apps.get_model('finance', 'FirmFinanceSettings')
    Invoice = apps.get_model('finance', 'Invoice')
    TH = Decimal('500000.00')
    billable = ('SENT', 'PARTIALLY_PAID', 'PAID', 'OVERDUE')

    for cab in Cabinet.objects.all():
        fs, _ = FirmFinanceSettings.objects.get_or_create(cabinet_id=cab.id)
        total = (
            Invoice.objects.filter(cabinet_id=cab.id, status__in=billable).aggregate(
                t=Sum('amount_ht')
            )['t']
            or Decimal('0')
        )
        fs.lifetime_ca = total
        if total >= TH:
            fs.is_tva_applicable = True
            if fs.tva_threshold_crossed_amount is None:
                fs.tva_threshold_crossed_amount = total
        fs.save()

    Invoice.objects.filter(tva_amount__gt=0).update(tva_applicable=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0011_finance_module'),
        ('finance', '0001_finance_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tva_applicable',
            field=models.BooleanField(default=False, help_text='Snapshot at creation time — never mutated after insert.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tva_exoneration_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='FirmFinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifetime_ca', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_tva_applicable', models.BooleanField(default=False)),
                ('tva_became_applicable_at', models.DateTimeField(blank=True, null=True)),
                ('tva_threshold_crossed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('threshold_notification_sent', models.BooleanField(default=False)),
                ('firm_created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cabinet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_settings', to='cabinets.cabinet')),
            ],
            options={
                'verbose_name': 'Firm Finance Settings',
            },
        ),
        migrations.RunPython(seed_firm_settings_and_backfill, noop_reverse),
    ]
