# Generated by Django 5.2.4 on 2026-03-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_specific_data',
            field=models.JSONField(blank=True, default=dict, help_text='Type-specific fields: consultation details, litigation details, or administrative details.'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('CONSULTATION', 'CONSULTATION'), ('LITIGATION', 'LITIGATION'), ('ADMINISTRATIVE', 'ADMINISTRATIVE')], db_index=True, default='LITIGATION', help_text='Discriminator: CONSULTATION | LITIGATION | ADMINISTRATIVE. Determines valid sub-fields.', max_length=50),
        ),
    ]
