# Generated by Django 5.2.4 on 2026-03-22 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_add_case_type_and_specific_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='converted_from_case',
            field=models.ForeignKey(blank=True, help_text='For LITIGATION/ADMINISTRATIVE: the original consultation. Null by default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_cases', to='cases.case'),
        ),
        migrations.AddField(
            model_name='case',
            name='converted_to_case',
            field=models.ForeignKey(blank=True, help_text='For CONSULTATION: the derived case created when converted. Null by default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_cases', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('CANCELLED', 'CANCELLED'), ('PENDING', 'PENDING'), ('ARCHIVED', 'ARCHIVED'), ('CONVERTED_TO_CASE', 'CONVERTED_TO_CASE')], default='OPEN', max_length=50),
        ),
    ]
