# Generated by Django 5.2.4 on 2026-03-22 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_add_conversion_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Cabinet member who last saved the case (set on each PATCH/PUT).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Cabinet member who created the case (user who called POST).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
