# Generated by Django 5.2.4 on 2026-03-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_add_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='financial_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('BILLED', 'BILLED'), ('PARTIALLY_PAID', 'PARTIALLY_PAID'), ('PAID', 'PAID'), ('OVERDUE', 'OVERDUE')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='total_billed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='case',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
