# Generated by Django 5.2.4 on 2026-08-26 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0013_assign_existing_cabinets'),
        ('cases', '0009_finance_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('C', 'Consultation'), ('L', 'Litigation'), ('A', 'Administrative')], max_length=1)),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='case',
            options={},
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_attorneys',
            field=models.ManyToManyField(blank=True, help_text='Additional attorneys assigned to this matter (primary is assigned_to).', related_name='consultation_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='email_confirmation_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='case',
            name='email_confirmation_status',
            field=models.CharField(blank=True, default='', help_text='SENT | FAILED | empty when not attempted.', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='follow_up_sequence',
            field=models.PositiveIntegerField(blank=True, help_text='1-based follow-up index under parent_consultation (F01, F02, …).', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='parent_consultation',
            field=models.ForeignKey(blank=True, help_text='For follow-up consultations: the original consultation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='cases.case'),
        ),
        migrations.AddField(
            model_name='caseattachment',
            name='linked_cases',
            field=models.ManyToManyField(blank=True, help_text='Additional matters that may access this file without duplicating storage.', related_name='shared_attachments', to='cases.case'),
        ),
        migrations.AddField(
            model_name='caseattachment',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='caseattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_attachments_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='reference',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='caseattachment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.case'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['cabinet', 'case_type'], name='cases_case_cabinet_841b78_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['cabinet', 'status'], name='cases_case_cabinet_8c94b9_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['cabinet', 'client'], name='cases_case_cabinet_538211_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['parent_consultation'], name='cases_case_parent__39e929_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['converted_to_case'], name='cases_case_convert_285a52_idx'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('cabinet', 'reference'), name='uniq_case_cabinet_reference'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_consultation__isnull', False)), fields=('parent_consultation', 'follow_up_sequence'), name='uniq_case_follow_up_sequence'),
        ),
        migrations.AddField(
            model_name='casereferencesequence',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_reference_sequences', to='cabinets.cabinet'),
        ),
        migrations.AddConstraint(
            model_name='casereferencesequence',
            constraint=models.UniqueConstraint(fields=('cabinet', 'kind', 'year'), name='uniq_case_reference_sequence'),
        ),
    ]
