# Generated by Django 5.2.4 on 2026-09-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_client_portal_consultations'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='privacy_mode',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Optional matter-level privacy override: STANDARD | PSEUDONYMIZED | PRIVATE. Empty inherits cabinet / project policy.', max_length=20),
        ),
    ]
