# Generated by Django 5.2.4 on 2025-08-13 10:24

import cabinets.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0003_alter_cabinet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='cabinet',
            name='commercial_register',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator(50, 'Commercial register cannot exceed 50 characters')], verbose_name='commercial register'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='ice',
            field=models.CharField(max_length=15, null=True, validators=[cabinets.models.validate_ice_length], verbose_name='ICE'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='legal_status',
            field=models.CharField(max_length=100, null=True, verbose_name='legal status'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='max_employee_count',
            field=models.PositiveIntegerField(default=1, max_length=50, verbose_name='Max employee count'),
        ),
    ]
