# Generated by Django 5.2.4 on 2025-08-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0004_remove_cabinet_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='founded_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
