# Generated by Django 5.1.5 on 2025-10-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0005_alter_cabinet_founded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='max_employee_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Max employee count'),
        ),
    ]
