# Generated by Django 5.1.5 on 2025-10-08 19:19

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0006_alter_cabinet_max_employee_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cabinet_role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('lawyer', 'Lawyer'), ('assistant', 'Assistant'), ('paralegal', 'Paralegal'), ('intern', 'Intern')], default='intern', help_text='Role of the cabinet member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cabinets.cabinet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cabinet')},
            },
        ),
    ]
