# Generated by Django 5.1.5 on 2025-11-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0008_update_cabinet_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinetmember',
            options={'ordering': ['-joined_at']},
        ),
        migrations.AddField(
            model_name='cabinetmember',
            name='custom_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cabinetmember',
            name='role',
            field=models.CharField(blank=True, choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('LAWYER', 'Lawyer'), ('ASSISTANT', 'Assistant'), ('VIEWER', 'Viewer')], default='VIEWER', help_text='Role of the cabinet member', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cabinetmember',
            name='cabinet_role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Admin'), ('lawyer', 'Lawyer'), ('assistant', 'Assistant'), ('paralegal', 'Paralegal'), ('intern', 'Intern')], default='intern', help_text='Legacy role field', max_length=20, null=True),
        ),
    ]
