# Generated by Django 5.2.4 on 2025-11-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0009_add_role_and_custom_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CabinetMember',
        ),
    ]
