# Generated by Django 5.2.4 on 2026-03-24 21:33

import cabinets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0010_delete_cabinetmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=cabinets.models.cabinet_logo_upload_to, verbose_name='logo'),
        ),
    ]
