# Generated by Django 5.2.4 on 2026-08-22 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0011_finance_module'),
        ('jurisdictions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cabinets', to='jurisdictions.jurisdiction'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='practice_type',
            field=models.CharField(blank=True, choices=[('LAW_OFFICE', 'Law Office'), ('LAW_FIRM', 'Law Firm')], db_index=True, max_length=20, null=True, verbose_name='practice type'),
        ),
    ]
