# Generated by Django 5.2.3 on 2025-06-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_activity_description_ar_activity_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
