# Generated by Django 5.2.3 on 2025-07-02 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0005_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='description_ar',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AddField(
            model_name='function',
            name='description_en',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AddField(
            model_name='function',
            name='description_fr',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AddField(
            model_name='function',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddField(
            model_name='function',
            name='name_en',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddField(
            model_name='function',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
