# Generated by Django 5.2.3 on 2025-07-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0006_function_description_ar_function_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='for_company',
            field=models.BooleanField(default=False),
        ),
    ]
