# Generated by Django 5.2.4 on 2025-07-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0008_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
