"""Notification type identifiers and priority levels."""

from __future__ import annotations


class NotificationPriority:
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    URGENT = "URGENT"

    CHOICES = (
        (LOW, "LOW"),
        (MEDIUM, "MEDIUM"),
        (HIGH, "HIGH"),
        (URGENT, "URGENT"),
    )


class NotificationType:
    # Tasks
    TASK_DUE_REMINDER_3DAYS = "TASK_DUE_REMINDER_3DAYS"
    TASK_OVERDUE = "TASK_OVERDUE"
    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_UPDATED = "TASK_UPDATED"
    TASK_COMPLETED = "TASK_COMPLETED"

    # Appointments
    APPOINTMENT_REMINDER_3DAYS = "APPOINTMENT_REMINDER_3DAYS"
    APPOINTMENT_DUE_TODAY = "APPOINTMENT_DUE_TODAY"
    APPOINTMENT_CREATED = "APPOINTMENT_CREATED"
    APPOINTMENT_UPDATED = "APPOINTMENT_UPDATED"

    # Cases
    CASE_ASSIGNED = "CASE_ASSIGNED"
    CASE_STATUS_UPDATED = "CASE_STATUS_UPDATED"
    CASE_UPDATED = "CASE_UPDATED"
    CASE_DEADLINE_3DAYS = "CASE_DEADLINE_3DAYS"
    CASE_DEADLINE_TODAY = "CASE_DEADLINE_TODAY"
    CASE_CONVERTED = "CASE_CONVERTED"
    CASE_HEARING_3DAYS = "CASE_HEARING_3DAYS"
    CASE_HEARING_TODAY = "CASE_HEARING_TODAY"

    # Profile & team
    PROFILE_UPDATED = "PROFILE_UPDATED"
    ROLE_CHANGED = "ROLE_CHANGED"
    MEMBER_ADDED = "MEMBER_ADDED"
    INVITATION_ACCEPTED = "INVITATION_ACCEPTED"
    JURIA_MEMBER_INVITED = "JURIA_MEMBER_INVITED"

    # Finance
    TVA_THRESHOLD_CROSSED = "TVA_THRESHOLD_CROSSED"
    INVOICE_OVERDUE = "INVOICE_OVERDUE"
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"

    # Chat / calls
    NEW_MESSAGE = "NEW_MESSAGE"
    NEW_MESSAGE_DAILY_REMINDER = "NEW_MESSAGE_DAILY_REMINDER"
    CALL_MISSED = "CALL_MISSED"


# Chat already has its own inbox; these must not appear in the activity panel.
IN_APP_HIDDEN_TYPES = frozenset(
    (
        NotificationType.NEW_MESSAGE,
        NotificationType.NEW_MESSAGE_DAILY_REMINDER,
    )
)
