# Generated by Django 5.2.4 on 2025-09-03 23:49

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='created_at',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
