# Generated by Django 5.2.4 on 2026-08-11 22:08

import dashboard.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_announcement_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='entity_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='entity_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='new_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='previous_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='media',
            field=models.FileField(blank=True, help_text='Optional. Images: jpg, png, gif, webp. Videos: mp4, webm, mov.', null=True, upload_to=dashboard.models.announcement_media_upload_to, validators=[dashboard.models.validate_announcement_media], verbose_name='Image or video'),
        ),
    ]
