# Generated by Django 5.2.4 on 2026-08-22 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0012_cabinet_jurisdiction_cabinet_practice_type'),
        ('dashboard', '0006_announcement_cms_fields'),
        ('jurisdictions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='jurisdictions.jurisdiction'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='visibility_scope',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('JURISDICTION', 'Jurisdiction'), ('CABINET', 'Cabinet')], db_index=True, default='CABINET', max_length=16),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='link_label',
            field=models.CharField(blank=True, default='', help_text='Optional. Shown on the dashboard button, e.g. "Learn more".', max_length=80, verbose_name='Learn more button text'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='link_url',
            field=models.CharField(blank=True, default='', help_text='Optional. Opens from the dashboard announcement. Use an in-app path such as /dashboard/juria, or a full HTTPS URL.', max_length=500, verbose_name='Learn more URL'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['visibility_scope', 'jurisdiction'], name='dash_ann_scope_jur_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('jurisdiction__isnull', True), ('visibility_scope', 'GLOBAL')), models.Q(('jurisdiction__isnull', False), ('visibility_scope', 'JURISDICTION')), ('visibility_scope', 'CABINET'), _connector='OR'), name='announcement_scope_jurisdiction_consistent'),
        ),
    ]
