# Generated by Django 5.2.4 on 2026-09-26 15:32

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinets', '0013_assign_existing_cabinets'),
        ('cases', '0012_privacy_gateway'),
        ('juria', '0006_privacy_gateway'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetPrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('default_mode', models.CharField(choices=[('STANDARD', 'Standard'), ('PSEUDONYMIZED', 'Pseudonymized'), ('PRIVATE', 'Private')], db_index=True, default='PSEUDONYMIZED', max_length=20)),
                ('require_pseudonymization_for_documents', models.BooleanField(default=True, help_text='Force Pseudonymized mode when documents or retrieved context are sent.')),
                ('reidentification_requires_authorization', models.BooleanField(default=True, help_text='Only cabinet staff may restore pseudonyms after AI responses.')),
                ('cabinet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_policy', to='cabinets.cabinet')),
            ],
            options={
                'verbose_name': 'cabinet privacy policy',
                'verbose_name_plural': 'cabinet privacy policies',
            },
        ),
        migrations.CreateModel(
            name='PseudonymMappingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jurisdiction_code', models.CharField(blank=True, default='', max_length=8)),
                ('mode', models.CharField(choices=[('STANDARD', 'Standard'), ('PSEUDONYMIZED', 'Pseudonymized'), ('PRIVATE', 'Private')], default='PSEUDONYMIZED', max_length=20)),
                ('entity_counts', models.JSONField(blank=True, default=dict, help_text='Counts by entity type only — never original values.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_sessions', to='cabinets.cabinet')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_sessions', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_sessions', to='juria.juriaproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PseudonymMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64)),
                ('entity_type', models.CharField(choices=[('PERSON', 'Person'), ('ORGANIZATION', 'Organization'), ('COMPANY', 'Company'), ('LOCATION', 'Location'), ('ADDRESS', 'Address'), ('DATE', 'Date'), ('PHONE', 'Phone'), ('EMAIL', 'Email'), ('IDENTIFIER', 'Identifier'), ('FINANCIAL', 'Financial information'), ('URL', 'URL')], db_index=True, max_length=32)),
                ('value_hash', models.CharField(help_text='HMAC of normalized value for stable token lookup within a session.', max_length=64)),
                ('encrypted_value', models.TextField(help_text='AES-256-GCM ciphertext (nonce + tag + ciphertext), base64-encoded.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cabinet', models.ForeignKey(help_text='Denormalized for cabinet queryset isolation.', on_delete=django.db.models.deletion.CASCADE, related_name='privacy_mappings', to='cabinets.cabinet')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='privacy.pseudonymmappingsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pseudonymmappingsession',
            index=models.Index(fields=['cabinet', 'created_at'], name='privacy_pse_cabinet_5a5a94_idx'),
        ),
        migrations.AddIndex(
            model_name='pseudonymmappingsession',
            index=models.Index(fields=['cabinet', 'project'], name='privacy_pse_cabinet_b655fc_idx'),
        ),
        migrations.AddIndex(
            model_name='pseudonymmapping',
            index=models.Index(fields=['cabinet', 'session'], name='privacy_pse_cabinet_6b3e05_idx'),
        ),
        migrations.AddIndex(
            model_name='pseudonymmapping',
            index=models.Index(fields=['cabinet', 'token'], name='privacy_pse_cabinet_494338_idx'),
        ),
        migrations.AddConstraint(
            model_name='pseudonymmapping',
            constraint=models.UniqueConstraint(fields=('session', 'token'), name='uniq_privacy_session_token'),
        ),
        migrations.AddConstraint(
            model_name='pseudonymmapping',
            constraint=models.UniqueConstraint(fields=('session', 'entity_type', 'value_hash'), name='uniq_privacy_session_entity_hash'),
        ),
    ]
