# Generated by Django 5.2.4 on 2026-08-22 16:34

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(db_index=True, help_text='Stable identifier, e.g. MA, QA. Never a display name.', max_length=8, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('name_fr', models.CharField(max_length=120, null=True)),
                ('name_en', models.CharField(max_length=120, null=True)),
                ('name_ar', models.CharField(max_length=120, null=True)),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2 country code.', max_length=2)),
                ('legal_system', models.CharField(blank=True, default='', max_length=64)),
                ('default_language', models.CharField(default='en', max_length=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=16)),
            ],
            options={
                'verbose_name': 'jurisdiction',
                'verbose_name_plural': 'jurisdictions',
                'ordering': ['code'],
            },
        ),
    ]
