# Generated by Django 5.2.4 on 2026-08-10 20:49

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinets', '0011_finance_module'),
        ('cases', '0009_finance_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('citation', models.CharField(blank=True, default='', help_text='Source / citation / legal reference (e.g. article, case cite).', max_length=512)),
                ('content', models.TextField(blank=True, default='', help_text='Key holding, findings, and relevance notes.')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_notes_authored', to=settings.AUTH_USER_MODEL)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_notes', to='cabinets.cabinet')),
                ('matter', models.ForeignKey(blank=True, help_text='Optional matter this note is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_notes', to='cases.case')),
            ],
            options={
                'ordering': ['-modified', '-created'],
                'indexes': [models.Index(fields=['cabinet', '-modified'], name='research_no_cabinet_de58c8_idx'), models.Index(fields=['cabinet', 'matter'], name='research_no_cabinet_439d58_idx')],
            },
        ),
    ]
