# Generated by Django 5.2.4

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_notes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="researchnote",
            index=models.Index(
                fields=["cabinet", "author", "-modified"],
                name="research_no_cab_author_idx",
            ),
        ),
    ]
