# Generated by Django 5.2.4 on 2026-09-13 13:58

import consultations.models
import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinets', '0013_assign_existing_cabinets'),
        ('cases', '0011_client_portal_consultations'),
        ('chat', '0012_appointment_participants_meeting_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('reference', models.CharField(db_index=True, max_length=32)),
                ('subject', models.CharField(max_length=255)),
                ('legal_area', models.CharField(choices=[('BUSINESS', 'Business law'), ('LABOR', 'Labor law'), ('REAL_ESTATE', 'Real estate law'), ('COMMERCIAL', 'Commercial law'), ('CORPORATE', 'Corporate law'), ('TAX', 'Tax law'), ('IP', 'Intellectual property'), ('DATA_PROTECTION', 'Data protection'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('description', models.TextField()),
                ('preferred_format', models.CharField(choices=[('CHAT', 'JURE Chat'), ('VIDEO', 'Video consultation'), ('PHONE', 'Phone'), ('IN_PERSON', 'In-person')], default='CHAT', max_length=20)),
                ('preferred_datetime', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('NEEDS_INFORMATION', 'Needs information'), ('ASSIGNED', 'Assigned'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined')], db_index=True, default='SUBMITTED', max_length=32)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High')], default='NORMAL', max_length=16)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consultation_requests', to=settings.AUTH_USER_MODEL)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='cabinets.cabinet')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to='chat.conversation')),
                ('related_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to='cases.case')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGED', 'Status changed'), ('LAWYER_ASSIGNED', 'Lawyer assigned'), ('COMMENT_ADDED', 'Comment added'), ('DOCUMENT_UPLOADED', 'Document uploaded'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('CHAT_ACTIVATED', 'Chat activated'), ('INFORMATION_REQUESTED', 'Information requested')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('client_visible', models.BooleanField(default=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_events', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='consultations.consultationrequest')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('content', models.TextField()),
                ('visibility', models.CharField(choices=[('CLIENT', 'Client-facing'), ('INTERNAL', 'Internal')], default='CLIENT', max_length=16)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_comments', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='consultations.consultationrequest')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', models.FileField(upload_to=consultations.models.consultation_attachment_upload_to)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='consultations.consultationrequest')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultationReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_request_sequences', to='cabinets.cabinet')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cabinet', 'year'), name='uniq_consultation_request_sequence')],
            },
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['cabinet', 'status'], name='consultatio_cabinet_a29699_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['cabinet', 'client'], name='consultatio_cabinet_d63d10_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['cabinet', 'assigned_lawyer'], name='consultatio_cabinet_c3e3a3_idx'),
        ),
    ]
