# Generated by Django 5.1.5 on 2025-08-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmembership',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
