# Generated by Django 5.2.4 on 2025-09-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_attachment_options_alter_call_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmembership',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
