# Generated by Django 5.2.4 on 2026-03-21 19:46

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_edit_delete_forward_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.conversation_icon_upload_to),
        ),
        migrations.AddField(
            model_name='conversation',
            name='icon_preset',
            field=models.CharField(blank=True, default='group', max_length=50),
        ),
    ]
