# Generated by Django 5.2.4 on 2026-08-25 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_message_call_history'),
        ('tasks', '0008_appointment_participants_meeting_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='temporary_for_appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_conversation', to='tasks.appointment'),
        ),
    ]
