# Generated by Django 5.2.4 on 2025-07-16 13:18

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import phonenumber_field.modelfields
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('commons', '0007_function_for_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='phone number')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='phone verified')),
                ('national_identity_card_front', models.ImageField(blank=True, null=True, upload_to='national_identity_card_front/', verbose_name='national identity card front')),
                ('national_identity_card_back', models.ImageField(blank=True, null=True, upload_to='national_identity_card_back/', verbose_name='national identity card back')),
                ('affiliation_code', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=50, unique=True, verbose_name='affiliation code')),
                ('birthday', models.DateField(validators=[users.models.validate_age_18_or_older], verbose_name='birthday')),
                ('is_auto_entrepreneur', models.BooleanField(blank=True, default=False, verbose_name='Is auto entrepreneur')),
                ('is_company', models.BooleanField(blank=True, default=False, verbose_name='Is company')),
                ('is_artisan', models.BooleanField(blank=True, default=False, verbose_name='Is artisan')),
                ('is_provider', models.BooleanField(blank=True, default=False, verbose_name='Is provider')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='company name')),
                ('trade_register', models.CharField(blank=True, max_length=100, null=True, verbose_name='trade register')),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='tax ID')),
                ('ice', models.CharField(blank=True, max_length=100, null=True, verbose_name='ICE')),
                ('other_activity', models.CharField(blank=True, max_length=255, null=True, verbose_name='other activity')),
                ('other_function', models.CharField(blank=True, max_length=255, null=True, verbose_name='other function')),
                ('iban', models.CharField(blank=True, max_length=24, null=True, validators=[users.models.validate_iban_length], verbose_name='International Bank Account Number')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.activity')),
                ('affiliated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated_users', to=settings.AUTH_USER_MODEL, verbose_name='affiliated by')),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.function')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('address', models.TextField(verbose_name='address')),
                ('osm_id', models.CharField(max_length=100, verbose_name='OSM ID')),
                ('type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('company', 'Company'), ('other', 'Other')], default='home', max_length=50, verbose_name='address type')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
