# Generated by Django 5.2.4 on 2025-07-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default=1, verbose_name='address'),
            preserve_default=False,
        ),
    ]
