# Generated by Django 5.2.4 on 2025-07-25 21:38

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_cabinet_member',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Cabinet Member'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, validators=[users.models.validate_age_18_or_older], verbose_name='birthday'),
        ),
    ]
