# Generated by Django 5.2.4 on 2025-07-26 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0003_alter_cabinet_owner'),
        ('users', '0003_user_is_cabinet_member_alter_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinets.cabinet'),
        ),
    ]
