# Generated by Django 5.2.4 on 2025-07-26 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0003_alter_cabinet_owner'),
        ('users', '0004_user_cabinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cabinet_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to='cabinets.cabinet'),
        ),
    ]
