# Generated by Django 5.2.4 on 2025-07-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_cabinet_creator'),
        ('users', '0006_user_image'),
    ]

    operations = [
    ]
