# Generated by Django 5.2.4 on 2025-08-13 10:24

import django.core.validators
import django_countries.fields
import phonenumber_field.modelfields
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_0005_user_cabinet_creator_0006_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='function',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ice',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_artisan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_auto_entrepreneur',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_provider',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_identity_card_back',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_identity_card_front',
        ),
        migrations.RemoveField(
            model_name='user',
            name='other_activity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='other_function',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trade_register',
        ),
        migrations.AddField(
            model_name='user',
            name='accept_data_processing',
            field=models.BooleanField(default=False, verbose_name='accept data processing'),
        ),
        migrations.AddField(
            model_name='user',
            name='accept_terms',
            field=models.BooleanField(default=False, verbose_name='accept terms'),
        ),
        migrations.AddField(
            model_name='user',
            name='bar_association',
            field=models.CharField(max_length=100, null=True, verbose_name='bar association'),
        ),
        migrations.AddField(
            model_name='user',
            name='bar_attestation',
            field=models.FileField(blank=True, null=True, upload_to='bar_attestations/', verbose_name='bar attestation'),
        ),
        migrations.AddField(
            model_name='user',
            name='bar_inscription_year',
            field=models.CharField(max_length=4, null=True, validators=[users.models.validate_bar_inscription_year], verbose_name='bar inscription year'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.FileField(blank=True, null=True, upload_to='national_ids/', verbose_name='national ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_card',
            field=models.FileField(blank=True, null=True, upload_to='professional_cards/', verbose_name='professional card'),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_card_number',
            field=models.CharField(max_length=50, null=True, validators=[users.models.validate_professional_card_number], verbose_name='professional card number'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='profile photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='trade_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100, 'Trade name cannot exceed 100 characters')], verbose_name='trade name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(100, 'Email cannot exceed 100 characters')], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'First name must contain at least 2 characters'), django.core.validators.MaxLengthValidator(50, 'First name cannot exceed 50 characters')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Last name must contain at least 2 characters'), django.core.validators.MaxLengthValidator(50, 'Last name cannot exceed 50 characters')], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, validators=[django.core.validators.MinLengthValidator(10, 'Phone number must contain at least 10 digits')], verbose_name='phone number'),
        ),
    ]
