# Generated by Django 5.2.4 on 2025-08-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_activity_remove_user_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='iban',
        ),
    ]
