# Generated by Django 5.2.4 on 2025-08-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_iban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trade_name',
        ),
        migrations.AddField(
            model_name='user',
            name='legal_status',
            field=models.CharField(max_length=100, null=True, verbose_name='legal status'),
        ),
    ]
