# Generated by Django 5.2.4 on 2025-08-19 17:30

import django_countries.fields
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_profile_photo_remove_user_trade_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bar_association',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='bar association'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bar_inscription_year',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[users.models.validate_bar_inscription_year], verbose_name='bar inscription year'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='legal_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='legal status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='professional_card_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[users.models.validate_professional_card_number], verbose_name='professional card number'),
        ),
    ]
