# Generated by Django 5.1.5 on 2025-10-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cabinet_role',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cabinet Role'),
        ),
    ]
