# Generated by Django 5.2.4 on 2025-11-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_update_signup_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cabinet_role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='structure_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team_size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trade_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('LAWYER', 'Lawyer'), ('ASSISTANT', 'Assistant'), ('VIEWER', 'Viewer')], default='VIEWER', help_text='Role of the cabinet member', max_length=20, null=True),
        ),
    ]
