# Generated by Django 5.2.4 on 2026-03-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_set_owner_role_for_cabinet_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MAD per hour — used for hourly fee calculation.', max_digits=8, null=True),
        ),
    ]
