# Generated by Django 5.2.4 on 2026-03-24 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice', models.CharField(blank=True, max_length=15, null=True)),
                ('if_number', models.CharField(blank=True, max_length=20, null=True)),
                ('client_type', models.CharField(choices=[('INDIVIDUAL', 'INDIVIDUAL'), ('COMPANY', 'COMPANY')], default='INDIVIDUAL', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firm_client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clients_client',
            },
        ),
    ]
