# Generated by Django 5.2.4 on 2025-08-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_cabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
