# Generated by Django 5.1.5 on 2025-09-04 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clear_invalid_client_data(apps, schema_editor):
    """
    Clear invalid client data before converting to ForeignKey.
    Since we're converting from CharField to ForeignKey, we need to clear
    any existing string values that can't be converted to valid user IDs.
    """
    Task = apps.get_model('tasks', 'Task')
    Appointment = apps.get_model('tasks', 'Appointment')
    
    # Clear client field for all tasks and appointments
    # This is safe because the field was optional (null=True, blank=True)
    Task.objects.all().update(client=None)
    Appointment.objects.all().update(client=None)


def reverse_clear_client_data(apps, schema_editor):
    """
    Reverse operation - no need to do anything since we're just clearing data
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_case_task_case_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
        # Clear invalid client data before schema change
        migrations.RunPython(clear_invalid_client_data, reverse_clear_client_data),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
