# Generated by Django 5.2.4 on 2026-08-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_backfill_task_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='participant_scope',
            field=models.CharField(choices=[('team', 'Team members'), ('with_client', 'With client')], default='team', max_length=20),
        ),
    ]
