# Generated by Django 5.2.4 on 2026-08-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_appointment_participants_meeting_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='participant_scope',
            field=models.CharField(choices=[('team', 'Team members'), ('with_client', 'With client')], db_default='team', default='team', max_length=20),
        ),
    ]
