# Generated by Django 5.1.5 on 2026-03-28 23:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0009_finance_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JuriaConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(choices=[('CHAT', 'CHAT'), ('CONTRACT_ANALYSIS', 'CONTRACT_ANALYSIS'), ('LEGAL_RESEARCH', 'LEGAL_RESEARCH'), ('DOCUMENT_DRAFTING', 'DOCUMENT_DRAFTING')], max_length=30)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juria_conversations', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juria_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JuriaMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('USER', 'USER'), ('ASSISTANT', 'ASSISTANT'), ('SYSTEM', 'SYSTEM')], max_length=10)),
                ('content', models.TextField()),
                ('mode', models.CharField(max_length=30)),
                ('has_attachment', models.BooleanField(default=False)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('attachment_type', models.CharField(blank=True, max_length=50)),
                ('attachment_path', models.CharField(blank=True, max_length=500)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('juria_message_id', models.CharField(blank=True, max_length=100)),
                ('generated_document_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='juria.juriaconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JuriaUsage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_messages', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('contract_analyses', models.IntegerField(default=0)),
                ('documents_drafted', models.IntegerField(default=0)),
                ('research_queries', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juria_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
