# Generated by Django 5.2.4 on 2026-08-29 14:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0013_assign_existing_cabinets'),
        ('cases', '0010_consultation_workflow'),
        ('juria', '0001_initial'),
        ('library', '0009_library_resource_metadata_favorites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='juriamessage',
            name='analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='juriamessage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juria_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='juriamessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juriamessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juriamessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='juriamessage',
            name='is_superseded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='juriamessage',
            name='language',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='juriamessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_messages', to='juria.juriamessage'),
        ),
        migrations.AddField(
            model_name='juriamessage',
            name='proposed_actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='juriamessage',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='juriamessage',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='juria.juriaconversation'),
        ),
        migrations.CreateModel(
            name='JuriaArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artifact_type', models.CharField(choices=[('MISE_EN_DEMEURE', 'Mise en demeure'), ('STATUTS_SARL', 'Statuts SARL'), ('PROCURATION', 'Procuration'), ('REQUETE', 'Requête'), ('CONTRAT_TRAVAIL', 'Contrat de travail'), ('CONCLUSIONS', 'Conclusions'), ('CONTRAT_BAIL', 'Contrat de bail'), ('AUTRE', 'Autre')], default='AUTRE', max_length=40)),
                ('content_html', models.TextField(blank=True, default='')),
                ('content_markdown', models.TextField(blank=True, default='')),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juria_artifacts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JuriaArtifactVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('content_html', models.TextField(blank=True, default='')),
                ('content_markdown', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='juria.juriaartifact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juria_artifact_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['version_number'],
            },
        ),
        migrations.CreateModel(
            name='JuriaMessageVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('version_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juria_message_versions', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='juria.juriamessage')),
            ],
            options={
                'ordering': ['version_number'],
            },
        ),
        migrations.CreateModel(
            name='JuriaProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ARCHIVED', 'ARCHIVED'), ('DELETED', 'DELETED')], db_index=True, default='ACTIVE', max_length=16)),
                ('preferred_language', models.CharField(choices=[('fr', 'French'), ('en', 'English'), ('ar', 'Arabic'), ('darija', 'Darija')], default='fr', max_length=16)),
                ('jurisdiction_code', models.CharField(choices=[('MA', 'Morocco'), ('FR', 'France'), ('AE', 'United Arab Emirates'), ('QA', 'Qatar'), ('OTHER', 'Other')], default='MA', max_length=8)),
                ('legal_domain', models.CharField(blank=True, default='', max_length=120)),
                ('instructions', models.TextField(blank=True, default='')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juria_projects', to='cabinets.cabinet')),
                ('duplicated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='juria.juriaproject')),
                ('linked_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juria_projects', to='cases.case')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_juria_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JuriaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='juria/project_files/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('file_kind', models.CharField(blank=True, default='', max_length=16)),
                ('size_bytes', models.IntegerField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('ocr_status', models.CharField(choices=[('PENDING', 'PENDING'), ('NOT_NEEDED', 'NOT_NEEDED'), ('REQUIRED', 'REQUIRED'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', max_length=16)),
                ('chunks', models.JSONField(blank=True, default=list)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juria_files_uploaded', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='juria.juriaproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JuriaComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('mentioned_user_ids', models.JSONField(blank=True, default=list)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='juria.juriaartifact')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juria_comments', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='juria.juriamessage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='juria.juriaproject')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='juriaartifact',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='juria.juriaproject'),
        ),
        migrations.CreateModel(
            name='JuriaActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('PROJECT_CREATED', 'PROJECT_CREATED'), ('PROJECT_UPDATED', 'PROJECT_UPDATED'), ('PROJECT_ARCHIVED', 'PROJECT_ARCHIVED'), ('PROJECT_RESTORED', 'PROJECT_RESTORED'), ('PROJECT_DELETED', 'PROJECT_DELETED'), ('PROJECT_DUPLICATED', 'PROJECT_DUPLICATED'), ('MEMBER_INVITED', 'MEMBER_INVITED'), ('MEMBER_REMOVED', 'MEMBER_REMOVED'), ('MEMBER_ROLE_CHANGED', 'MEMBER_ROLE_CHANGED'), ('DOCUMENT_ADDED', 'DOCUMENT_ADDED'), ('DOCUMENT_REMOVED', 'DOCUMENT_REMOVED'), ('CASE_LINKED', 'CASE_LINKED'), ('CASE_UNLINKED', 'CASE_UNLINKED'), ('THREAD_CREATED', 'THREAD_CREATED'), ('THREAD_ARCHIVED', 'THREAD_ARCHIVED'), ('ARTIFACT_CREATED', 'ARTIFACT_CREATED'), ('ARTIFACT_MODIFIED', 'ARTIFACT_MODIFIED'), ('ARTIFACT_EXPORTED', 'ARTIFACT_EXPORTED'), ('PERMISSION_CHANGED', 'PERMISSION_CHANGED'), ('SOURCE_ADDED', 'SOURCE_ADDED'), ('SOURCE_REMOVED', 'SOURCE_REMOVED')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juria_activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='juria.juriaproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='juriaconversation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_conversations', to='juria.juriaproject'),
        ),
        migrations.CreateModel(
            name='JuriaProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'OWNER'), ('EDITOR', 'EDITOR'), ('REVIEWER', 'REVIEWER'), ('VIEWER', 'VIEWER')], default='VIEWER', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juria_members_invited', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='juria.juriaproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juria_project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JuriaProjectPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource', models.CharField(choices=[('CASE', 'CASE'), ('DOCUMENTS', 'DOCUMENTS'), ('LIBRARY', 'LIBRARY'), ('CALENDAR', 'CALENDAR'), ('TASKS', 'TASKS'), ('CLIENTS', 'CLIENTS'), ('TEAM', 'TEAM')], max_length=20)),
                ('level', models.CharField(choices=[('NONE', 'NONE'), ('READ', 'READ'), ('CREATE', 'CREATE'), ('UPDATE', 'UPDATE')], default='NONE', max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='juria.juriaproject')),
            ],
        ),
        migrations.CreateModel(
            name='JuriaProjectSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CASE', 'CASE'), ('CASE_DOCUMENT', 'CASE_DOCUMENT'), ('LIBRARY', 'LIBRARY'), ('LIBRARY_LOCAL', 'LIBRARY_LOCAL'), ('LIBRARY_INTERNATIONAL', 'LIBRARY_INTERNATIONAL'), ('CALENDAR', 'CALENDAR'), ('TASKS', 'TASKS'), ('CLIENT', 'CLIENT'), ('TEAM', 'TEAM'), ('UPLOAD', 'UPLOAD')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juria_sources_added', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juria_sources', to='cases.case')),
                ('case_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juria_sources', to='cases.caseattachment')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juria_client_sources', to=settings.AUTH_USER_MODEL)),
                ('juria_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='juria.juriafile')),
                ('library_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juria_sources', to='library.document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='juria.juriaproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JuriaThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('mode', models.CharField(choices=[('CHAT', 'CHAT'), ('CONTRACT_ANALYSIS', 'CONTRACT_ANALYSIS'), ('LEGAL_RESEARCH', 'LEGAL_RESEARCH'), ('DOCUMENT_DRAFTING', 'DOCUMENT_DRAFTING')], default='CHAT', max_length=30)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juria_threads_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='juria.juriaproject')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='juriaartifact',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='juria.juriathread'),
        ),
        migrations.AddField(
            model_name='juriaconversation',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_conversations', to='juria.juriathread'),
        ),
        migrations.AddField(
            model_name='juriamessage',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='juria.juriathread'),
        ),
        migrations.AddIndex(
            model_name='juriamessage',
            index=models.Index(fields=['thread', 'created_at'], name='juria_juria_thread__c10719_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='juriaartifactversion',
            unique_together={('artifact', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='juriamessageversion',
            unique_together={('message', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='juriaproject',
            index=models.Index(fields=['cabinet', 'status'], name='juria_juria_cabinet_fbc809_idx'),
        ),
        migrations.AddIndex(
            model_name='juriaproject',
            index=models.Index(fields=['cabinet', 'owner'], name='juria_juria_cabinet_7b2857_idx'),
        ),
        migrations.AddIndex(
            model_name='juriaactivity',
            index=models.Index(fields=['project', '-created_at'], name='juria_juria_project_1a13ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='juriaprojectmember',
            unique_together={('project', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='juriaprojectpermission',
            unique_together={('project', 'resource')},
        ),
        migrations.AddIndex(
            model_name='juriaprojectsource',
            index=models.Index(fields=['project', 'kind'], name='juria_juria_project_dfe1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='juriathread',
            index=models.Index(fields=['project', 'is_archived', 'is_deleted'], name='juria_juria_project_cb6ffe_idx'),
        ),
    ]
