# Generated by Django 5.2.4 on 2026-09-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juria', '0005_ai_chat_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='juriaproject',
            name='privacy_mode',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Optional project privacy override: STANDARD | PSEUDONYMIZED | PRIVATE. Empty inherits case / cabinet policy.', max_length=20),
        ),
        migrations.AlterField(
            model_name='juriaactivity',
            name='action',
            field=models.CharField(choices=[('PROJECT_CREATED', 'PROJECT_CREATED'), ('PROJECT_UPDATED', 'PROJECT_UPDATED'), ('PROJECT_ARCHIVED', 'PROJECT_ARCHIVED'), ('PROJECT_RESTORED', 'PROJECT_RESTORED'), ('PROJECT_DELETED', 'PROJECT_DELETED'), ('PROJECT_DUPLICATED', 'PROJECT_DUPLICATED'), ('MEMBER_INVITED', 'MEMBER_INVITED'), ('MEMBER_REMOVED', 'MEMBER_REMOVED'), ('MEMBER_ROLE_CHANGED', 'MEMBER_ROLE_CHANGED'), ('DOCUMENT_ADDED', 'DOCUMENT_ADDED'), ('DOCUMENT_REMOVED', 'DOCUMENT_REMOVED'), ('CASE_LINKED', 'CASE_LINKED'), ('CASE_UNLINKED', 'CASE_UNLINKED'), ('THREAD_CREATED', 'THREAD_CREATED'), ('THREAD_ARCHIVED', 'THREAD_ARCHIVED'), ('ARTIFACT_CREATED', 'ARTIFACT_CREATED'), ('ARTIFACT_MODIFIED', 'ARTIFACT_MODIFIED'), ('ARTIFACT_EXPORTED', 'ARTIFACT_EXPORTED'), ('PERMISSION_CHANGED', 'PERMISSION_CHANGED'), ('SOURCE_ADDED', 'SOURCE_ADDED'), ('SOURCE_REMOVED', 'SOURCE_REMOVED'), ('PRIVACY_SCAN_STARTED', 'PRIVACY_SCAN_STARTED'), ('PII_DETECTED', 'PII_DETECTED'), ('DOCUMENT_PSEUDONYMIZED', 'DOCUMENT_PSEUDONYMIZED'), ('AI_REQUEST_SANITIZED', 'AI_REQUEST_SANITIZED'), ('AI_REQUEST_SENT', 'AI_REQUEST_SENT'), ('AI_RESPONSE_RECEIVED', 'AI_RESPONSE_RECEIVED'), ('REIDENTIFICATION_REQUESTED', 'REIDENTIFICATION_REQUESTED'), ('REIDENTIFICATION_COMPLETED', 'REIDENTIFICATION_COMPLETED'), ('PRIVACY_GATEWAY_BLOCKED', 'PRIVACY_GATEWAY_BLOCKED')], max_length=48),
        ),
    ]
